# Generated by Django 5.0.3 on 2024-03-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegame',
            name='language_id',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
